### ISSUE TITLE
Rain toggle doesn't work

### ISSUE THREAD

**Issue by pegla2108001** [Declipsonator/Particle-Blocker#1]
Toggling rain off doesn't seem to have any effect
Tested with just fabric API and installer

![particleblocker-bugreport-allon](https://user-images.githubusercontent.com/47089475/168908657-68674072-93cf-4d72-92f8-c3791bc98c8d.png)

![particleblocker-bugreport-alloff](https://user-images.githubusercontent.com/47089475/168908655-71a99f49-104b-47ec-9b43-66a6f58ec218.png)

**Comment by Declipsonator** [comment]
Hello there, 
What is happening here is that the particle **_rain_** is not actually the main drops. Instead its the splashes you see on the ground. Rain itself is not rendered as a particle. All the particles are named based on how mojang names them in the code, so I don't control what they are called. As a result I am closing this issue since its not really a bug.

![image](https://user-images.githubusercontent.com/96392121/173165848-d7f9dfff-d517-4b58-a165-ec618140cab3.png)
